In [1]:
import sys
from utils.path import get_git_root
sys.path.insert(0, get_git_root().as_posix())

from utils.api_client import APIClient
from scripts.config import API_PUB_BASE_URL, RT_PACKAGE_PARAMS

client = APIClient(API_PUB_BASE_URL, RT_PACKAGE_PARAMS)
client.get_endpoints()

{'system regions': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/system_regions',
 'system_information': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/system_information',
 'station_information': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_information',
 'station_status': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_status',
 'system_pricing_plans': 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/system_pricing_plans'}

In [2]:
station_endpoint = client.fetch_data("station_information")
station_endpoint["last_updated"]

1781837404

In [3]:
station_info = station_endpoint["data"]["stations"]
station_info

[{'station_id': '7000',
  'external_id': 'f8aa7900-e9c7-11ef-984e-124c66246c7d',
  'name': 'Fort York  Blvd / Capreol Ct',
  'physical_configuration': 'REGULAR',
  'lat': 43.639832,
  'lon': -79.395954,
  'altitude': None,
  'address': 'Fort York  Blvd / Capreol Ct',
  'capacity': 47,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Fort York - Entertainment District'],
  'obcn': '647-643-9607',
  'short_name': '647-643-9607',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7001',
  'external_id': 'f8aaeb6e-e9c7-11ef-984e-124c66246c7d',
  'name': 'Wellesley Station Green P',
  'physical_configuration': 'ELECTRICBIKESTATION',
  'lat': 43.66496415990742,
  'lon': -79.38355031526893,
  'altitude': None,
  'address': 'Yonge / Wellesley',
  'post_code': 'M4Y 1G7',
  'capacity': 23,
  'is_charging_station': True,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['E-Charging ', 'South', 'Church Wellesley / Yorkville'],
  'obcn': '416-617-9576',
  'short_name': '416-617-9576',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7002',
  'external_id': 'f8aaef03-e9c7-11ef-984e-124c66246c7d',
  'name': 'St. George St / Bloor St W',
  'physical_configuration': 'REGULAR',
  'lat': 43.66713121831853,
  'lon': -79.3995550638237,
  'altitude': None,
  'address': 'St. George St / Bloor St W',
  'capacity': 19,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'U of T - Hospital Row'],
  'obcn': '647-643-9615',
  'short_name': '647-643-9615',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7003',
  'external_id': 'f8ab20ac-e9c7-11ef-984e-124c66246c7d',
  'name': 'Madison Ave / Bloor St W',
  'physical_configuration': 'REGULAR',
  'lat': 43.66701830465472,
  'lon': -79.4027958687172,
  'altitude': None,
  'address': 'Madison Ave / Bloor St W',
  'capacity': 15,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Bloor St W / Annex'],
  'obcn': '647-631-4587',
  'short_name': '647-631-4587',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7005',
  'external_id': 'f8ab51f8-e9c7-11ef-984e-124c66246c7d',
  'name': 'King St W / York St',
  'physical_configuration': 'VAULT',
  'lat': 43.6480008,
  'lon': -79.383177,
  'altitude': 0.0,
  'address': 'King St W / York St',
  'capacity': 23,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'phone'],
  'groups': ['South', 'Financial District'],
  'obcn': '647-643-9693',
  'short_name': '647-643-9693',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7006',
  'external_id': 'f8ab54c0-e9c7-11ef-984e-124c66246c7d',
  'name': 'Bay St / College St (East Side)',
  'physical_configuration': 'REGULAR',
  'lat': 43.660439,
  'lon': -79.385525,
  'altitude': None,
  'address': 'Bay St / College St (East Side)',
  'capacity': 31,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'is_valet_station': False,
  'groups': ['South', 'U of T - Hospital Row'],
  'obcn': '416-569-2349',
  'short_name': '416-569-2349',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7007',
  'external_id': 'f8ab576d-e9c7-11ef-984e-124c66246c7d',
  'name': 'College St / Huron St',
  'physical_configuration': 'REGULAR',
  'lat': 43.658148,
  'lon': -79.398167,
  'altitude': None,
  'address': 'College St / Huron St',
  'capacity': 19,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'U of T - Hospital Row'],
  'obcn': '647-625-3582',
  'short_name': '647-625-3582',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7008',
  'external_id': 'f8ab5a3f-e9c7-11ef-984e-124c66246c7d',
  'name': "Wellesley St W / Queen's Park Cres",
  'physical_configuration': 'REGULAR',
  'lat': 43.663376,
  'lon': -79.392125,
  'altitude': None,
  'address': "Wellesley St W / Queen's Park Cres",
  'capacity': 19,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'U of T - Hospital Row'],
  'obcn': '647-643-9648',
  'short_name': '647-643-9648',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7010',
  'external_id': 'f8ab5fcc-e9c7-11ef-984e-124c66246c7d',
  'name': 'King St W / Spadina Ave',
  'physical_configuration': 'REGULAR',
  'lat': 43.64514249449372,
  'lon': -79.39510358283808,
  'altitude': None,
  'address': 'King St W / Spadina Ave',
  'capacity': 19,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Fort York - Entertainment District'],
  'obcn': '647-202-6537',
  'short_name': '647-202-6537',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7013',
  'external_id': 'f8ab675c-e9c7-11ef-984e-124c66246c7d',
  'name': 'Scott St / The Esplanade',
  'physical_configuration': 'REGULAR',
  'lat': 43.64659663170443,
  'lon': -79.37530913867988,
  'altitude': 0.0,
  'address': 'Scott St / The Esplanade',
  'post_code': 'M5E 1Z4',
  'capacity': 19,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Financial District'],
  'obcn': '416-666-6440',
  'short_name': '416-666-6440',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7014',
  'external_id': 'f8ab69cf-e9c7-11ef-984e-124c66246c7d',
  'name': 'Sherbourne St / Carlton St (Allan Gardens)',
  'physical_configuration': 'REGULAR',
  'lat': 43.663102,
  'lon': -79.373181,
  'altitude': None,
  'address': 'Sherbourne St / Carlton St (Allan Gardens)',
  'capacity': 17,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['East', 'Church Wellesley / Yorkville'],
  'obcn': '416-710-6764',
  'short_name': '416-710-6764',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7015',
  'external_id': 'f8ab6c2a-e9c7-11ef-984e-124c66246c7d',
  'name': 'King St W / Bay St (West Side)',
  'physical_configuration': 'REGULAR',
  'lat': 43.64852,
  'lon': -79.380576,
  'altitude': None,
  'address': 'King St W / Bay St (West Side)',
  'capacity': 39,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'is_valet_station': False,
  'groups': ['Valet Stations', 'South', 'Financial District'],
  'obcn': '416-671-7595',
  'short_name': '416-671-7595',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7016',
  'external_id': 'f8ab6eb0-e9c7-11ef-984e-124c66246c7d',
  'name': 'Bay St / Queens Quay W (Ferry Terminal)',
  'physical_configuration': 'REGULAR',
  'lat': 43.640978,
  'lon': -79.376785,
  'altitude': None,
  'address': 'Bay St / Queens Quay W (Ferry Terminal)',
  'post_code': 'M5J',
  'capacity': 35,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'is_valet_station': False,
  'groups': ['South', 'Watefront'],
  'obcn': '647-271-1378',
  'short_name': '647-271-1378',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7017',
  'external_id': 'f8ab715f-e9c7-11ef-984e-124c66246c7d',
  'name': 'Widmer St / Adelaide St W - SMART',
  'physical_configuration': 'SMARTMAPFRAME',
  'lat': 43.647547634759206,
  'lon': -79.39155200496292,
  'altitude': 0.0,
  'address': 'Widmer St / Adelaide St W',
  'post_code': 'M5V 1J9',
  'capacity': 12,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'phone'],
  'groups': ['South', 'Fort York - Entertainment District'],
  'obcn': '647-631-9958',
  'short_name': '647-631-9958',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7018',
  'external_id': 'f8ab73f6-e9c7-11ef-984e-124c66246c7d',
  'name': 'Bremner Blvd / Rees St',
  'physical_configuration': 'REGULAR',
  'lat': 43.641529,
  'lon': -79.386741,
  'altitude': None,
  'address': 'Bremner Blvd / Rees St',
  'cross_street': 'Bremner Blvd / Rees St',
  'capacity': 48,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'is_valet_station': False,
  'groups': ['South', 'Watefront'],
  'obcn': '647-669-0947',
  'short_name': '647-669-0947',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7019',
  'external_id': 'f8ab7671-e9c7-11ef-984e-124c66246c7d',
  'name': 'Temperance St Station',
  'physical_configuration': 'VAULT',
  'lat': 43.650945,
  'lon': -79.379498,
  'altitude': None,
  'address': 'Temperance St. Station',
  'post_code': 'M5H 1Y6',
  'capacity': 55,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'phone'],
  'is_valet_station': False,
  'groups': ['Valet Stations', 'South', 'Financial District'],
  'obcn': '9 Temperance St .',
  'short_name': '9 Temperance St .',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7020',
  'external_id': 'f8ab796c-e9c7-11ef-984e-124c66246c7d',
  'name': 'Phoebe St / Spadina Ave',
  'physical_configuration': 'REGULAR',
  'lat': 43.650033,
  'lon': -79.396555,
  'altitude': None,
  'address': 'Phoebe St / Spadina Ave',
  'capacity': 33,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Fort York - Entertainment District'],
  'obcn': '647-621-5766',
  'short_name': '647-621-5766',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7021',
  'external_id': 'f8acb80a-e9c7-11ef-984e-124c66246c7d',
  'name': 'Bay St / Albert St',
  'physical_configuration': 'REGULAR',
  'lat': 43.653264,
  'lon': -79.382458,
  'altitude': None,
  'address': 'Bay St / Albert St',
  'capacity': 63,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Financial District'],
  'obcn': '647-643-9652',
  'short_name': '647-643-9652',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7023',
  'external_id': 'f8ad026d-e9c7-11ef-984e-124c66246c7d',
  'name': 'College St / Borden St',
  'physical_configuration': 'REGULAR',
  'lat': 43.6571,
  'lon': -79.4056,
  'altitude': None,
  'address': 'College St / Borden St',
  'capacity': 11,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'College St - Harbord St'],
  'obcn': '647-643-9629',
  'short_name': '647-643-9629',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7024',
  'external_id': 'f8ad04fa-e9c7-11ef-984e-124c66246c7d',
  'name': 'Dundonald St / Church St',
  'physical_configuration': 'REGULAR',
  'lat': 43.66663,
  'lon': -79.38148,
  'altitude': 0.0,
  'address': 'Dundonald St / Church St',
  'capacity': 38,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Church Wellesley / Yorkville'],
  'obcn': '647-631-9859',
  'short_name': '647-631-9859',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7025',
  'external_id': 'f8ad0779-e9c7-11ef-984e-124c66246c7d',
  'name': 'Ted Rogers Way / Bloor St E',
  'physical_configuration': 'VAULT',
  'lat': 43.671293,
  'lon': -79.380471,
  'altitude': None,
  'address': 'Ted Rogers Way / Bloor St E',
  'capacity': 27,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'phone'],
  'groups': ['East', 'Church Wellesley / Yorkville'],
  'obcn': '647-631-9970',
  'short_name': '647-631-9970',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7026',
  'external_id': 'f8ad0a28-e9c7-11ef-984e-124c66246c7d',
  'name': 'Bay St / St. Joseph St',
  'physical_configuration': 'REGULAR',
  'lat': 43.665527,
  'lon': -79.387499,
  'altitude': None,
  'address': 'Bay St / St. Joseph St',
  'capacity': 15,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'U of T - Hospital Row'],
  'obcn': '416-666-0783',
  'short_name': '416-666-0783',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7027',
  'external_id': 'f8ad0c95-e9c7-11ef-984e-124c66246c7d',
  'name': 'Beverley St / Dundas St W',
  'physical_configuration': 'REGULAR',
  'lat': 43.652823,
  'lon': -79.393388,
  'altitude': None,
  'address': 'Beverley  St / Dundas St W',
  'capacity': 31,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Fort York - Entertainment District'],
  'obcn': '647-621-6739',
  'short_name': '647-621-6739',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7028',
  'external_id': 'f8ad0ee6-e9c7-11ef-984e-124c66246c7d',
  'name': 'Gould St / Mutual St',
  'physical_configuration': 'VAULT',
  'lat': 43.6582,
  'lon': -79.3768,
  'altitude': None,
  'address': 'Gould St / Mutual St',
  'capacity': 31,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'phone'],
  'groups': ['South', 'Financial District'],
  'obcn': '416-560-7261',
  'short_name': '416-560-7261',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7029',
  'external_id': 'f8ad113b-e9c7-11ef-984e-124c66246c7d',
  'name': 'Bay St / Bloor St W (East Side)',
  'physical_configuration': 'REGULAR',
  'lat': 43.66943,
  'lon': -79.38915,
  'altitude': None,
  'address': '1199 Bay St',
  'post_code': 'M6G1X2',
  'capacity': 15,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['North', 'Church Wellesley / Yorkville'],
  'obcn': '647-669-3457',
  'short_name': '647-669-3457',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7030',
  'external_id': 'f8ad1392-e9c7-11ef-984e-124c66246c7d',
  'name': 'Bay St / Wellesley St W',
  'physical_configuration': 'REGULAR',
  'lat': 43.664088,
  'lon': -79.387095,
  'altitude': None,
  'address': 'Bay St / Wellesley St W',
  'capacity': 35,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'is_valet_station': False,
  'groups': ['South', 'U of T - Hospital Row'],
  'obcn': '647-643-9612',
  'short_name': '647-643-9612',
  'nearby_distance': 1609.34,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7031',
  'external_id': 'f8ad15ed-e9c7-11ef-984e-124c66246c7d',
  'name': 'Jarvis St / Isabella St',
  'physical_configuration': 'VAULT',
  'lat': 43.668991,
  'lon': -79.379385,
  'altitude': None,
  'address': 'Jarvis St / Isabella St',
  'capacity': 39,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'phone'],
  'is_valet_station': False,
  'groups': ['East', 'Church Wellesley / Yorkville'],
  'obcn': '416-569-7503',
  'short_name': '416-569-7503',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7032',
  'external_id': 'f8ad1836-e9c7-11ef-984e-124c66246c7d',
  'name': 'Augusta Ave / Dundas St W',
  'physical_configuration': 'REGULAR',
  'lat': 43.652473,
  'lon': -79.401456,
  'altitude': None,
  'address': 'Augusta Ave / Dundas St W',
  'capacity': 15,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'College St - Harbord St'],
  'obcn': '647-622-8139',
  'short_name': '647-622-8139',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7033',
  'external_id': 'f8ad1af4-e9c7-11ef-984e-124c66246c7d',
  'name': 'Union Station',
  'physical_configuration': 'REGULAR',
  'lat': 43.645609,
  'lon': -79.380386,
  'altitude': 1.0,
  'address': 'Union Station',
  'post_code': 'M5J1E3',
  'capacity': 43,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['Valet Stations', 'South', 'Financial District'],
  'obcn': '647-620-1494',
  'short_name': '647-620-1494',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7034',
  'external_id': 'f8ad1d3d-e9c7-11ef-984e-124c66246c7d',
  'name': 'Church St / Bloor St E',
  'physical_configuration': 'REGULAR',
  'lat': 43.671389,
  'lon': -79.382919,
  'altitude': None,
  'address': 'Church St / Bloor St E',
  'cross_street': '11',
  'capacity': 15,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['North', 'Church Wellesley / Yorkville'],
  'obcn': '437-992-7029',
  'short_name': '437-992-7029',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7035',
  'external_id': 'f8ad1fd2-e9c7-11ef-984e-124c66246c7d',
  'name': 'Queen St W / Ossington Ave',
  'physical_configuration': 'REGULAR',
  'lat': 43.643975,
  'lon': -79.419576,
  'altitude': None,
  'address': 'Queen St W / Ossington Ave',
  'capacity': 43,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['West', 'Liberty Village - Queen West'],
  'obcn': '416-371-6632',
  'short_name': '416-371-6632',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7036',
  'external_id': 'f8ad222f-e9c7-11ef-984e-124c66246c7d',
  'name': 'Trinity St /Front St E',
  'physical_configuration': 'REGULAR',
  'lat': 43.651318,
  'lon': -79.36023,
  'altitude': None,
  'address': 'Trinity St / Front St E',
  'capacity': 19,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['East', 'Regent Park - Distillery'],
  'obcn': '416-816-5603',
  'short_name': '416-816-5603',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7037',
  'external_id': 'f8af0ce1-e9c7-11ef-984e-124c66246c7d',
  'name': 'Bathurst St / Dundas St W',
  'physical_configuration': 'VAULT',
  'lat': 43.65220761646196,
  'lon': -79.4055689857289,
  'altitude': None,
  'address': 'Bathurst St / Dundas St W',
  'post_code': 'M5T 2S3',
  'capacity': 41,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'phone'],
  'groups': ['South', 'College St - Harbord St'],
  'obcn': '647-621-8042',
  'short_name': '647-621-8042',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7038',
  'external_id': 'f8af1118-e9c7-11ef-984e-124c66246c7d',
  'name': 'Dundas St W / Yonge St',
  'physical_configuration': 'REGULAR',
  'lat': 43.656094,
  'lon': -79.381484,
  'altitude': None,
  'address': 'Dundas St W / Yonge St',
  'capacity': 31,
  'is_charging_station': False,
  'rental_methods': ['key', 'transitcard', 'creditcard', 'phone'],
  'groups': ['South', 'Financial District'],
  'obcn': '647-643-9714',
  'short_name': '647-643-9714',
  'nearby_distance': 500.0,
  '_ride_code_support': True,
  'rental_uris': {}},
 {'station_id': '7039',
  'external_id': 'f8af1407-e9c7-11ef-984e-124c66246c7d',
  'name': 'Simcoe St / Michael Sweet Ave',
  'physical_configuration': 'REGULAR',

In [4]:
import pandas as pd

df = pd.DataFrame(station_info)
df.head()

,station_id,external_id,name,physical_configuration,lat,lon,altitude,address,capacity,is_charging_station,...,groups,obcn,short_name,nearby_distance,_ride_code_support,rental_uris,post_code,is_valet_station,cross_street,_valet_station_details
0,7000,f8aa7900-e9c7-11ef-984e-124c66246c7d,Fort York Blvd / Capreol Ct,REGULAR,43.639832,-79.395954,NaN,Fort York Blvd / Capreol Ct,47,False,...,"[South, Fort York - Entertainment District]",647-643-9607,647-643-9607,500.0,True,{},NaN,NaN,NaN,NaN
1,7001,f8aaeb6e-e9c7-11ef-984e-124c66246c7d,Wellesley Station Green P,ELECTRICBIKESTATION,43.664964,-79.383550,NaN,Yonge / Wellesley,23,True,...,"[E-Charging , South, Church Wellesley / Yorkvi...",416-617-9576,416-617-9576,500.0,True,{},M4Y 1G7,NaN,NaN,NaN
2,7002,f8aaef03-e9c7-11ef-984e-124c66246c7d,St. George St / Bloor St W,REGULAR,43.667131,-79.399555,NaN,St. George St / Bloor St W,19,False,...,"[South, U of T - Hospital Row]",647-643-9615,647-643-9615,500.0,True,{},NaN,NaN,NaN,NaN
3,7003,f8ab20ac-e9c7-11ef-984e-124c66246c7d,Madison Ave / Bloor St W,REGULAR,43.667018,-79.402796,NaN,Madison Ave / Bloor St W,15,False,...,"[South, Bloor St W / Annex]",647-631-4587,647-631-4587,500.0,True,{},NaN,NaN,NaN,NaN
4,7005,f8ab51f8-e9c7-11ef-984e-124c66246c7d,King St W / York St,VAULT,43.648001,-79.383177,0.0,King St W / York St,23,False,...,"[South, Financial District]",647-643-9693,647-643-9693,500.0,True,{},NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1046 entries, 0 to 1045
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   station_id              1046 non-null   object
 1   external_id             1046 non-null   object
 2   name                    1046 non-null   object
 3   physical_configuration  1043 non-null   object
 4   lat                     1046 non-null   float64
 5   lon                     1046 non-null   float64
 6   altitude                659 non-null    float64
 7   address                 1045 non-null   object
 8   capacity                1046 non-null   int64
 9   is_charging_station     1046 non-null   bool
 10  rental_methods          1043 non-null   object
 11  groups                  1046 non-null   object
 12  obcn                    1046 non-null   object
 13  short_name              1046 non-null   object
 14  nearby_distance         1046 non-null   float64
 15  _ride_code_support      1046 non-null   bool
 16  rental_uris             1046 non-null   object
 17  post_code               755 non-null    object
 18  is_valet_station        40 non-null     object
 19  cross_street            380 non-null    object
 20  _valet_station_details  3 non-null      object
dtypes: bool(2), float64(4), int64(1), object(14)
memory usage: 157.4+ KB

In [6]:
df["altitude"].unique()

array([   nan,   0.  ,   1.  , 102.08])

In [7]:
df["is_valet_station"].unique()

array([nan, False, True], dtype=object)

In [8]:
df["nearby_distance"].nunique()

35

In [9]:
# drop altitude, groups, obc, rental_uris, _ride_code_support, cross_street, is_valet_station
cleaned = df.drop(columns=["altitude", "groups", "obcn", "rental_uris", "_ride_code_support", "cross_street", "is_valet_station"])
cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1046 entries, 0 to 1045
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   station_id              1046 non-null   object
 1   external_id             1046 non-null   object
 2   name                    1046 non-null   object
 3   physical_configuration  1043 non-null   object
 4   lat                     1046 non-null   float64
 5   lon                     1046 non-null   float64
 6   address                 1045 non-null   object
 7   capacity                1046 non-null   int64
 8   is_charging_station     1046 non-null   bool
 9   rental_methods          1043 non-null   object
 10  short_name              1046 non-null   object
 11  nearby_distance         1046 non-null   float64
 12  post_code               755 non-null    object
 13  _valet_station_details  3 non-null      object
dtypes: bool(1), float64(3), int64(1), object(9)
memory usage: 107.4+ KB

In [10]:
cleaned["physical_configuration"].unique()

array(['REGULAR', 'ELECTRICBIKESTATION', 'VAULT', 'SMARTMAPFRAME', nan],
      dtype=object)

In [11]:
cleaned[cleaned["physical_configuration"].isna()]

,station_id,external_id,name,physical_configuration,lat,lon,address,capacity,is_charging_station,rental_methods,short_name,nearby_distance,post_code,_valet_station_details
643,7794,f8c983a7-e9c7-11ef-984e-124c66246c7d,York St / Harbour St (Love Park),NaN,43.641017,-79.380359,York St / Harbour St (Love Park),16,False,NaN,96 Queens Quay W,350.0,M5J,NaN
956,8147,581b99ab-da3e-11f0-b51f-1214620ec1db,Widmer St / Adelaide St W (South),NaN,43.647300,-79.391313,Widmer St / Adelaide St W (South),8,False,NaN,Widmer St / Adelaide St W,20.0,M5V 2E8,NaN
957,8148,581b9c51-da3e-11f0-b51f-1214620ec1db,Simcoe St / Wellington St W (North) 2,NaN,43.646246,-79.385489,Simcoe St / Wellington St W,4,False,NaN,Simcoe St / Wellington St W,10.0,M5J 0C2,NaN

In [12]:
cleaned[cleaned["address"].isna()]

,station_id,external_id,name,physical_configuration,lat,lon,address,capacity,is_charging_station,rental_methods,short_name,nearby_distance,post_code,_valet_station_details
689,7844,f8ca3017-e9c7-11ef-984e-124c66246c7d,Second St / Lake Shore Blvd W,VAULT,43.601915,-79.499419,NaN,15,False,"[key, transitcard, phone]",Ward 3 - (2765 Lake Shore Blvd W),350.0,M8V 1H2,NaN

In [13]:
cleaned[cleaned["name"] == cleaned["address"]].shape[0]

653

In [14]:
#set all nulls to the station name
cleaned["address"].fillna(cleaned["name"], inplace=True)

/var/folders/kx/0yxjmr611n9b7fnqf983rl700000gn/T/ipykernel_34527/2573472537.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned["address"].fillna(cleaned["name"], inplace=True)

In [15]:
cleaned[cleaned["name"] == cleaned["address"]].shape[0]

654

In [25]:
#replace missing config, rental methods, and postal code with "UNKNOWN"
df.columns[df.isnull().any()].tolist()

['physical_configuration',
 'altitude',
 'address',
 'rental_methods',
 'post_code',
 'is_valet_station',
 'cross_street',
 '_valet_station_details']

In [ ]:
#cast dtype

In [18]:
station_status = client.fetch_data("station_status")
station_status["last_updated"]

1781837538

In [22]:
status_df = pd.DataFrame(station_status["data"]["stations"])
status_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1046 entries, 0 to 1045
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   station_id                 1046 non-null   object
 1   num_bikes_available        1046 non-null   int64
 2   num_bikes_disabled         1046 non-null   int64
 3   is_charging_station        1046 non-null   bool
 4   status                     1046 non-null   object
 5   traffic                    0 non-null      object
 6   num_bikes_available_types  1046 non-null   object
 7   num_docks_available        1046 non-null   int64
 8   num_docks_disabled         1046 non-null   int64
 9   last_reported              1046 non-null   int64
 10  is_installed               1046 non-null   int64
 11  is_renting                 1046 non-null   int64
 12  is_returning               1046 non-null   int64
dtypes: bool(1), int64(8), object(4)
memory usage: 99.2+ KB

In [23]:
status_df.head()

,station_id,num_bikes_available,num_bikes_disabled,is_charging_station,status,traffic,num_bikes_available_types,num_docks_available,num_docks_disabled,last_reported,is_installed,is_renting,is_returning
0,7000,42,3,False,IN_SERVICE,None,"{'mechanical': 41, 'ebike': 1}",1,1,1781837441,1,1,1
1,7001,2,4,True,IN_SERVICE,None,"{'mechanical': 2, 'ebike': 0}",17,0,1781837439,1,1,1
2,7002,0,2,False,IN_SERVICE,None,"{'mechanical': 0, 'ebike': 0}",16,1,1781837494,1,1,1
3,7003,1,2,False,IN_SERVICE,None,"{'mechanical': 0, 'ebike': 1}",12,0,1781837517,1,1,1
4,7005,0,0,False,IN_SERVICE,None,"{'mechanical': 0, 'ebike': 0}",23,0,1781837488,1,1,1